export const img1 = require('./season_coll_1_img_large.webp')
export const img2 = require('./season_coll_2_img_large.webp')
export const img3 = require('./season_coll_3_img_large.webp')
export const img4 = require('./season_coll_4_img_large.webp')
export const img5 = require('./season_coll_5_img_large.webp')
export const img6 = require('./season_coll_6_img_large.webp')
